### ISSUE TITLE
Fails to build with latest Wayfire

### ISSUE THREAD

**Issue by jbeich** [Javyre/swayfire#41]
Regressed by https://github.com/wayfirewm/wayfire/commit/a79978b20b0d.
```c++
In file included from src/core/binding.cpp:2:
src/core/core.hpp:1182:34: error: no type named 'view_change_viewport_signal' in namespace 'wf'; did you mean 'view_change_workspace_signal'?
                dynamic_cast<wf::view_change_viewport_signal *>(data_);
                             ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                 view_change_workspace_signal
/usr/include/wayfire/signal-definitions.hpp:604:8: note: 'view_change_workspace_signal' declared here
struct view_change_workspace_signal : public _view_signal
       ^
```

**Comment by jbeich** [comment]
I confirm, builds fine now.
